### ISSUE TITLE
Dynamic config manager not functional in 4.4

### ISSUE THREAD

**Issue by alexcern** [openshift/router#107]
While trying the 4.4 router, I noticed that [enabling the dynamic configuration manager](https://docs.openshift.com/container-platform/3.11/install_config/router/default_haproxy_router.html#using-the-dynamic-configuration-manager) in a custom router deployment results in the router failing to start.

The following error is seen in the router pod logs:
 
```
E0324 18:57:02.396551       1 limiter.go:165] error executing template for file /var/lib/haproxy/conf/haproxy.config: template: haproxy-config.template:498:65: executing "/var/lib/haproxy/conf/haproxy.config" at <$cfgIdx>: wrong type for value; expected string; got templaterouter.ServiceAliasConfigKey
```

It seems that the change of type in https://github.com/openshift/router/pull/51 forgot some functions used only with the dynamic configuration manager. It looks like an easy fix that I'm happy to provide.

But that raises a question: @ramr @smarterclayton is the dynamic config manager still supported in Openshift 4? We are preparing the migration from Openshift 3.11 and I'm afraid we really need it: we have applications with many long-standing (websocket) connections. If the router reloads configuration often, old haproxy processes tend to stay around to keep those connections alive and accumulate to the point of exhausting all available memory on router nodes. The dynamic config manager alleviates the problem considerably.

**Comment by ironcladlou** [comment]
The dynamic configuration manager isn't currently supported in OpenShift v4. We don't have any plans yet to re-enable it, and we may end up using a different approach entirely to enable the optimizations the dynamic config manager was created to address. Unfortunately I don't have any concrete timeline for you at the moment.

**Comment by alexcern** [comment]
Thanks for the clarification @ironcladlou

Would you still consider this small PR fixing the issue until some official solution comes up? #108

**Comment by ironcladlou** [comment]
Absolutely, thanks!
