### ISSUE TITLE
Container fails healthchecks when deploying Openshift cluster

### ISSUE THREAD

**Issue by SriRamanujam** [openshift/router#11]
#### Description
The service router fails to come up properly when deploying a fresh Openshift 3.11 cluster.

##### Steps To Reproduce
1. Run through Ansible installation playbooks manually in the order specified in table 1 of this section: https://docs.openshift.com/container-platform/3.11/install/running_install.html#advanced-retrying-installation
2. Keep an eye on `oc get all` after running `playbooks/openshift-hosted/config.yml`
3. Note that the router pod does not start up correctly and enters an error state.

##### Expected Results
The router pod comes up without issue.

##### Observed Results
The router pod consistently fails the health check and eventually enters an error state. 

`oc get logs` from the crashing pod only shows this:
```
I0212 18:53:59.815075       1 template.go:297] Starting template router (v3.11.0+d0c29df-98)
I0212 18:53:59.817021       1 metrics.go:147] Router health and metrics port listening at 0.0.0.0:1936 on HTTP and HTTPS
E0212 18:53:59.823534       1 haproxy.go:392] can't scrape HAProxy: dial unix /var/lib/haproxy/run/haproxy.sock: connect: no such file or directory
I0212 18:54:29.279496       1 router.go:252] Router is including routes in all namespaces
```

##### Additional Information

I was able to get a shell into the container briefly before Openshift restarted it, and I noticed that the haproxy process was happily running, so it might be that the healthcheck is the only thing failing.

Operating system:
```
# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)
```

Router docker image:
```
docker.io/openshift/origin-haproxy-router    v3.11.0             c5b0420ab52a        3 days ago          407 MB
```

**Comment by datapresso** [comment]
Is there any update on this issue? We are encountering the same issue.
In addition, the cluster console is up but not accessible and possibly due to this issue.
We are using:
```
[root@w02ocp01 node]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core) 
[root@w02ocp01 node]# rpm -q openshift-ansible
openshift-ansible-3.11.37-1.git.0.3b8b341.el7.noarch
[root@w02ocp01 node]# ansible --version
ansible 2.6.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

```[root@w02ocp01 node]# kubectl logs router-1-pdbpz -n default
I0916 04:55:24.440062       1 template.go:297] Starting template router (v3.11.0+739ab57-285)
I0916 04:55:24.445638       1 metrics.go:147] Router health and metrics port listening at 0.0.0.0:1936 on HTTP and HTTPS
E0916 04:55:24.454934       1 haproxy.go:392] can't scrape HAProxy: dial unix /var/lib/haproxy/run/haproxy.sock: connect: no such file or directory
I0916 04:55:24.606739       1 router.go:481] Router reloaded:
 - Checking http://localhost:80 ...
 - Health check ok : 0 retry attempt(s).
I0916 04:55:24.606776       1 router.go:252] Router is including routes in all namespaces
I0916 04:55:24.835480       1 router.go:481] Router reloaded:
 - Checking http://localhost:80 ...
 - Health check ok : 0 retry attempt(s).
I0916 04:55:29.836159       1 router.go:481] Router reloaded:
 - Checking http://localhost:80 ...
```

**Comment by SriRamanujam** [comment]
In our case, this issue was due to a misconfigured hosts file on our nodes. Once we fixed that, the cluster came up without issue.

**Comment by freeeflyer** [comment]
> In our case, this issue was due to a misconfigured hosts file on our nodes. Once we fixed that, the cluster came up without issue.

Could you tell me what was the misconfiguration like ?

**Comment by SriRamanujam** [comment]
I don't quite remember the exact details anymore, but it was something to do with duplicate and/or extra entries in `/etc/hosts` for the... container registry, I believe. My pre-setup Ansible playbook had a typo in it, so it ended up creating duplicate hosts entries and for whatever reason that messed up the ingress controller on the master.

**Comment by blackandred** [comment]
Hi,

When I try to extend somehow the original container I get this error.
No matter what I do eg. I add "RUN haproxy -version" then I get this error.
It's not possible for me to overwrite the router base image.

```
I1203 08:20:28.164818       1 template.go:297] Starting template router (v3.11.0+0731b2f-347)
I1203 08:20:28.177812       1 metrics.go:147] Router health and metrics port listening at 0.0.0.0:1936 on HTTP and HTTPS
E1203 08:20:28.198029       1 haproxy.go:392] can't scrape HAProxy: dial unix /var/lib/haproxy/run/haproxy.sock: connect: no such file or directory
I1203 08:20:28.354422       1 router.go:252] Router is including routes in all namespaces
E1203 08:20:28.556299       1 router_controller.go:250] another route has claimed this host
E1203 08:20:28.589812       1 haproxy.go:392] can't scrape HAProxy: dial unix /var/lib/haproxy/run/haproxy.sock: connect: connection refused
E1203 08:20:28.643249       1 limiter.go:137] error reloading router: exit status 1
[ALERT] 336/082028 (24) : Starting frontend public: cannot bind socket [0.0.0.0:80]
[ALERT] 336/082028 (24) : Starting frontend public_ssl: cannot bind socket [0.0.0.0:443]
E1203 08:20:33.588445       1 haproxy.go:392] can't scrape HAProxy: dial unix /var/lib/haproxy/run/haproxy.sock: connect: connection refused
E1203 08:20:33.630604       1 limiter.go:137] error reloading router: exit status 1
[ALERT] 336/082033 (27) : Starting frontend public: cannot bind socket [0.0.0.0:80]
[ALERT] 336/082033 (27) : Starting frontend public_ssl: cannot bind socket [0.0.0.0:443]
```
