### ISSUE TITLE
Router overwrites X-Forwarded-Host/Port/Proto headers

### ISSUE THREAD

**Issue by merusso** [openshift/router#207]
The router's current behavior overwrites X-Forwarded-Host, X-Forwarded-Port, and X-Forwarded-Proto. Instead, I believe that a more appropriate behavior would be to preserve these header values, so the existing values will be passed downstream.

New config changes added in PR #134 allow for this behavior to be adjusted at the route level via annotations, but when using the `append` option (the new default), these headers are *still replaced*.

### Example

So imagine the following:

* We have a setup where there's a load balancer sitting between clients and the OpenShift cluster
* This load balancer strips HTTPS, sending HTTP to the cluster but preserving the client values with X-Forwarded-* headers
* There's an application running in OpenShift which handles requests for the public-facing endpoint "https://myapp.openshift.company.com"

When receiving requests, this app wants to know what protocol/port a client uses to connect to this endpoint. It can know this by looking at the X-Forwarded-Proto/Port headers passed to it from upstream systems, but this is only true if all upstream systems preserve these values passed by the client. In this router implementation, the load balancer will pass "X-Forwarded-Proto: https, X-Forwarded-Port: 443", but the router will overwrite these headers with "X-Forwarded-Proto: http, X-Forwarded-Port: 80", losing the real values passed by the originating client to the public-facing endpoint, so the application won't know if the client is actually connecting over HTTP or HTTPS.

Instead, if the router preserved these headers, the app would receive "X-Forwarded-Proto: https, X-Forwarded-Port: 443" and know that the client connected to the public-facing endpoint via HTTPS:443.

**Comment by merusso** [comment]
/remove-lifecycle stale

I still think this is an important, useful improvement.

**Comment by merusso** [comment]
Can we discuss whether this issue has merit? I had a good discussion with @Miciah about this implementation in a prior PR: https://github.com/openshift/router/pull/134#issuecomment-702923309 but that conversation fell off and probably wasn't the right place to discuss the topic anyway.

**Comment by sgreene570** [comment]
> Can we discuss whether this issue has merit? I had a good discussion with @Miciah about this implementation in a prior PR: [#134 (comment)](https://github.com/openshift/router/pull/134#issuecomment-702923309) but that conversation fell off and probably wasn't the right place to discuss the topic anyway.

Hi @merusso . Thanks for bringing this issue to our attention. We don't actively check github issues for this repo. Instead, we track issues / bugs via Red Hat Bugzilla.

If you don't mind, you could open a new bug (https://bugzilla.redhat.com/enter_bug.cgi) under the "OpenShift Container Platform" product, "Routing" sub-component. If you could include the information you've shared here, plus any additional details and or testing, that would be great! Thanks! This way, the network edge team will be able to collaborate more easily and prioritize this issue among our other open bugs.

**Comment by merusso** [comment]
Will do, thanks for the info!

**Comment by merusso** [comment]
We recently upgraded our OpenShift cluster from v4.4 to v4.6 and I'm happy to report that this problem appears to have been resolved. The behavior I now experience is that the headers X-Forwarded-Host, X-Forwarded-Port, and X-Forwarded-Proto are being appended, which is expected behavior for the new `append` option.

**Comment by sgreene570** [comment]
> We recently upgraded our OpenShift cluster from v4.4 to v4.6 and I'm happy to report that this problem appears to have been resolved. The behavior I now experience is that the headers X-Forwarded-Host, X-Forwarded-Port, and X-Forwarded-Proto are being appended, which is expected behavior for the new `append` option.

sounds good, thanks for letting us know!
/close
