### ISSUE TITLE
Route CRD does not have a OpenAPI structural schema

### ISSUE THREAD

**Issue by SDBrett** [openshift/router#213]
`apiexentions.k8s.io/v1beta1` was depreciated in K8S 1.16 and will be unavailable from K8S version 1.22 and the CRD will need to use `apiexentions.k8s.io/v1`. 

Changing the manifest to `apiexentions.k8s.io/v1` introduces a mandatory requirement for CRDs include a structural schema. https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema

I'm happy to work on adding the schema into the CRD manifest but, will need some assistance to understand the structure further.

**Comment by David-Crty** [comment]
In order to improve DevExp and IDE integration it would be great to have a proper CRD with the correct doc.
