### ISSUE TITLE
Make HAProxy config editable via environment of router

### ISSUE THREAD

**Issue by mhorst00** [openshift/router#281]
Currently, it is not easily possible to edit the config of the HAProxy running in the automatically generated router pod of the standard ingress operator of OKD. 
This would be necessary to, for example, use larger GET-Requests through the standard OKD ingress operator by changing tune.bufsize in the haproxy.cfg to a bigger value.

Is it possible to make these kind of config changes via environment variables of the ingress deployment for the router pods?

**Comment by sgreene570** [comment]
In OCP/OKD 4.8, users will be able to specify some new Ingress Controller tuning options, such as `tune.bufsize` and `tune.nbthreads`.

**Comment by sgreene570** [comment]
See https://github.com/openshift/api/blob/master/operator/v1/types_ingress.go#L1027-L1082
