### ISSUE TITLE
Concatenation of key and cert causing failure

### ISSUE THREAD

**Issue by trexx** [openshift/router#294]
I'm attempting to use cert-manager backed by Vault to provide OpenShift 4.7.11 with a custom console certificate.
I unfortunately have come across an issue caused by the concatenation of certificate and private key which results in an unexpected format causing haproxy to fail.

The cause of this failure is due to this snippet in /var/lib/haproxy/router/certs/default.pem

-----END CERTIFICATE----------BEGIN PRIVATE KEY-----

It seems OpenShift expects there to be a linefeed
If I alter the secret base64 to include a line return after the certificate, haproxy successfully starts but since I like the certificates to be managed by cert-manager, this isn't a solution.

**Comment by absynth76** [comment]
Hello, we are impacted by the same issue, any comment on this please ?

**Comment by trexx** [comment]
I would suggest opening a support case with Redhat instead who can then create a BZ case for this.
You can also point them to this "solution" posted in 2019  which doesn't at all fix the problem if your certificate source is from an API such as Vault PKI engine or cert-manager.
https://access.redhat.com/solutions/4252991

**Comment by absynth76** [comment]
you are right, I found a bugzilla issue that talks about the issue: https://bugzilla.redhat.com/show_bug.cgi?id=1961811

**Comment by Jamstah** [comment]
Bugzilla is closed, so /close

**Comment by Jamstah** [comment]
/close

Bugzilla is closed
