### ISSUE TITLE
Set custom headers via annotation

### ISSUE THREAD

**Issue by michael-wirth** [openshift/router#327]
The "haproxy.router.openshift.io/rewrite-target" and the "haproxy.router.openshift.io/set-forwarded-headers" are great and useful annotation, but unfortunately incomplete.

It would be really great if also the "x-forwarded-prefix" header could be set automatically (calculating the diff between the matching path and the rewrite target) or by setting the header specifically within its own annotation.

It would be awesome to be able to set any kind of additional header with an annotation.

Without, it's just a poor man's proxy function, which can't be used for applications that don't use hard-coded base URLs.

**Comment by ssams** [comment]
+1

found this whilst trying to deploy an application which requires a "x-forwarded-prefix" header to work on a sub-path, without this I need to change deployment domains or add extra reverse proxies just to add a single header.

**Comment by adhanshe-tibco** [comment]
@michael-wirth I see you closed this as completed, can you please help us with the solution. We are dealing with the same problem. 

Thank you.
