### ISSUE TITLE
Missing haproxy24-2.4.1-1.el8.x86_64.rpm for hacking

### ISSUE THREAD

**Issue by shark300** [openshift/router#412]
I followed the steps in the HACKING.md guide.

Unfortunately, the build was failed with the following error message:

> [MIRROR] haproxy24-2.4.1-1.el8.x86_64.rpm: Status code: 404 for https://github.com/frobware/haproxy-hacks/raw/master/RPMs/haproxy24-2.4.1-1.el8.x86_64.rpm (IP: 140.82.121.3)
[MIRROR] haproxy24-2.4.1-1.el8.x86_64.rpm: Status code: 404 for https://github.com/frobware/haproxy-hacks/raw/master/RPMs/haproxy24-2.4.1-1.el8.x86_64.rpm (IP: 140.82.121.3)
[MIRROR] haproxy24-2.4.1-1.el8.x86_64.rpm: Status code: 404 for https://github.com/frobware/haproxy-hacks/raw/master/RPMs/haproxy24-2.4.1-1.el8.x86_64.rpm (IP: 140.82.121.3)
[MIRROR] haproxy24-2.4.1-1.el8.x86_64.rpm: Status code: 404 for https://github.com/frobware/haproxy-hacks/raw/master/RPMs/haproxy24-2.4.1-1.el8.x86_64.rpm (IP: 140.82.121.3)
[FAILED] haproxy24-2.4.1-1.el8.x86_64.rpm: Status code: 404 for https://github.com/frobware/haproxy-hacks/raw/master/RPMs/haproxy24-2.4.1-1.el8.x86_64.rpm (IP: 140.82.121.3)

I tried to download the listed file, but I got an error message:

> The 'frobware/haproxy-builds' repository doesn't contain the 'RPMs/haproxy24-2.4.1-1.el8.x86_64.rpm' path in 'master'.

As I see, it relates to the moving of RPMs folder of haproxy-builds:

> Moved to https://github.com/frobware/haproxy-builds/tree/master/RPMs

Unfortunately, this file is missing at the mentioned repository. As I see, it is impossible to build a hacking without this file.

**Comment by frobware** [comment]
> Unfortunately, this file is missing at the mentioned repository. As I see, it is impossible to build a hacking without this file.

You can substitute the referenced RPM with https://github.com/frobware/haproxy-builds/raw/master/RPMs/haproxy22-2.2.20-1.el8.x86_64.rpm. 

As mentioned in commit https://github.com/openshift/router/commit/06dcec9675eee98a3d55d40a6c259eba2399be18

> Note that the files and instructions provided in this commit are intended for Router development and are not officially supported or guaranteed to work.

**Comment by shark300** [comment]
Hi @frobware 
Thanks you for your help, I change it locally.
