### ISSUE TITLE
[Question] not under active development anymore, do you have alternative plans for haproxy router?

### ISSUE THREAD

**Issue by alibo** [openshift/router#415]
Hi everyone, I'm monitoring the development of the openshift/router for several months and it looks like Openshift doesn't have any plan on developing haproxy router anymore. It feels like it's an abandoned project This is the list of features many ingress/gateway API controllers are supporting:

- (True) Hot reload - in a mid or large cluster, it's reloaded almost every 5 seconds and creates lots of haproxy processes - (I know they can be adjusted, but the result is still not good, especially if you have many websocket/long-running connections)
- Data plain API v2 is not supported (it can be used for hot reload) 
- Supporting HTTP2 is still limited (edge termination, custom certificate, grpc, ...)
- Less visibility on incoming traffic (e.g. only response time of last 1024 requests are monitored by haproxy, no histogram metrics, ...) - requires a custom-made log parser
- Tracing is not supported
- Mirroring/Traffic-shadowing and canary release are not supported
- Even with having Ingress/V1 and GatewayAPI/v1Beta, Route object is still the first-citizen object in openshift platform for ingress traffic + no console UI feature for the other official objects
- Limited integration with 3rd-party tools (argo-rollout, flux, ...)
- No support for Global rate limiting
- No support for External authentication and authorization
- No support for Basic and JWT authentication
- Using older versions of HAProxy (2.2)
- No plan for supporting http3/quic (it's added to haproxy 2.6+)
- Routing based on header/query string
- Modifying/adding/removing headers
- Not supporting GatewayAPI
- Not having a clear roadmap
- ...

With that said, my question is that is this project has a future? or it's just an abandoned project and openshift is working on or planning for alternative options?

**Comment by mcurry-rh** [comment]
OpenShift will continue to fully support HAproxy for the foreseeable future.  We do not support all features of HAProxy, but we do support a prioritized set of customer-driven highly-valued features.  Most if not all of the features you cite are either supported by another feature of the product (e.g. canary, console, tracing), on our published roadmap (e.g. HAProxy 2.6), or are currently in development (e.g. Gateway API).  If your organization requires support of a feature not already supported or in-progress, please work with your account team to submit a formal enhancement request.  If you would like more information about our roadmap, we publish a new roadmap presentation ("OpenShift: What's Next?") about 3 times a year, and you can find them here: https://www.redhat.com/en/whats-new-red-hat-openshift

**Comment by alibo** [comment]
@mcurry-rh thank you for your clarification, I've already seen the roadmap. I'll discuss our requirements with the rest of the team so we can work on a formal enhancement request. (although, we're in the middle of migration to another ingress controller for our internal users using our in-development [route-to-ingress operator](https://github.com/snapp-incubator/route-to-ingress-operator))

I'll close this issue as I get my answer, but feel free to open it for further discussion.
