### ISSUE TITLE
No option to preserve the session affinity cookie emitted by a server

### ISSUE THREAD

**Issue by pferraro** [openshift/router#446]
The HAProxy ingress controller exposes the annotation `haproxy-ingress.github.io/session-cookie-preserve` to prevent HAProxy from overwriting a session affinity cookie written by a backend server.  See: https://haproxy-ingress.github.io/docs/configuration/keys/#affinity
OpenShift's router seems to lack such configuration.
There also seems to be no way to disable the use of "indirect", which makes it impossible for a backend server to see the affinity cookie sent by the client.
This can be disabled via the HAProxy ingress controller using the annotation `haproxy-ingress.github.io/session-cookie-keywords`

**Comment by candita** [comment]
Moved to RFE: https://issues.redhat.com/browse/RFE-5580
/close
