### ISSUE TITLE
certificate key is stored in the route object instead of secret

### ISSUE THREAD

**Issue by zfrhv** [openshift/router#493]
### Problem
when using route with tls termination edge/reencrypt and providing new custom certificate, the certificate+ private key is being stored in the route object itself.
and the only way to store the certificate key is [in the route object](https://docs.openshift.com/container-platform/4.12/networking/routes/secured-routes.html)

### Why its bad
this is bad because any user with read only permissions on the cluster/namespace can view the private key via sinply running `oc get route -o yaml` and inspect all the traffic

### Comparison and workaround
even kubernetes uses secrets, [see here](https://kubernetes.github.io/ingress-nginx/examples/tls-termination/)

i have tried to use kubernetes ingress instead of route, but openshift automatically creates a new route, pulls out my private key from the secret and appends it to the route object.
so i cant even workaround

**Comment by nate-duke** [comment]
I know that i've read this discussed before so i've done some looking around. https://github.com/openshift/cert-manager-operator/issues/60#issuecomment-1097615352 implies that there are concerns around route controller compromise leading to exposure of *all* secrets in the cluster, not just TLS private keys for routes but i've been unable to find the source of that.

**Comment by zfrhv** [comment]
thank you for the fast reply

as i understood this issue is already in progress and will be fixed in openshift 4.14?

and a workaround is to install the cert manager operator and use annotations same as with ingress?

**Comment by nate-duke** [comment]
@zfrhv I'm not sure. I'm just a community member and user. I do not work for IBM nor speak for the project.

**Comment by zfrhv** [comment]
@nate-duke i see
well thank you for the explanation
i guess i will close the case as it seems to be duplicate of the [cert manager issue](https://github.com/openshift/cert-manager-operator/issues/60#issuecomment-1097615352) (not sure in which repo this issue should exist tho
