### ISSUE TITLE
Would a Pull Request for `send-proxy` support be accepted?

### ISSUE THREAD

**Issue by darkedges** [openshift/router#497]
Morning
Would a Pull Request for `send-proxy` support be accepted? We want to enable it on backend servers that use 
```
tls:
    termination: "passthrough"
```

I am proposing 
- `haproxy.router.openshift.io/proxy_protocol: true`
- `haproxy.router.openshift.io/proxy_protocol_v2: true`

**Comment by candita** [comment]
@darkedges can you describe what you need in more detail?  We wouldn't be likely accept a PR that works using new router annotations.
