### ISSUE TITLE
Need help to turn on debugging of haproxy

### ISSUE THREAD

**Issue by olivermccarthy** [openshift/router#58]
https://docs.openshift.com/container-platform/3.9/admin_guide/router.html documents how to set DEBUG_LEVEL .
But I am working with openshift 4.2
When I try to edit the deployment and add 
````
ROUTER_LOG_LEVEL=debug
kubectl edit deployment router-default -n openshift-ingress
````
My changes get overwritten by the ingress operator

**Comment by Miciah** [comment]
Changing the log level is not supported in OpenShift 4.2.  However, there is an **unofficial**, **unsupported** way to enable debug logging:
```shell
oc -n openshift-ingress-operator annotate ingresscontrollers/default ingress.operator.openshift.io/unsupported-logging=debug
```
After enabling this annotation, each router pod will have a sidecar named "syslog" with the debug logs:
```shell
oc -n openshift-ingress logs deployments/router-default -c syslog -f
```

**Comment by olivermccarthy** [comment]
thank you .
