### ISSUE TITLE
`parseIPList` Function fails to process all valid IPs When a invalid entries is present in router whitelist ip list

### ISSUE THREAD

**Issue by mJace** [openshift/router#620]
### Description

The `parseIPList` function currently fails to handle IP lists that contain both valid and invalid IPs or CIDRs. When the function encounters an invalid entry, it immediately returns an empty string, which prevents any valid IPs from being processed or returned.

### Expected Behavior

- The function should process the entire list of IPs or CIDRs.
- It should return a string of all valid IPs and CIDRs, even if there are some invalid entries.
- Invalid entries should be logged for debugging purposes, but they should not cause the function to exit prematurely.

### Current Behavior

- The function returns an empty string as soon as it encounters an invalid IP or CIDR.
- No valid IPs are returned if any invalid entries are found.

### Steps to Reproduce

1. Provide a list of IPs or CIDRs that includes both valid and invalid entries to the `parseIPList` function.
2. Observe that the function returns an empty string, regardless of the valid entries present.

### Suggested Solution

Modify the `parseIPList` function to:
- Collect valid IPs and CIDRs while logging invalid ones.
- Return a space-separated string of valid IPs and CIDRs.
- Log all invalid entries for visibility and debugging.

### Additional Information

- A recent PR addresses this issue by enhancing the function to handle mixed validity lists more gracefully.
- This change improves the robustness of IP list processing and provides better insights into invalid entries.

**Comment by mJace** [comment]
Related PR https://github.com/openshift/router/pull/621

**Comment by candita** [comment]
Replaced by https://issues.redhat.com/browse/OCPBUGS-39403.
/close
