### ISSUE TITLE
Router metrics don't expose 4xx

### ISSUE THREAD

**Issue by metalmatze** [openshift/router#81]
Is there a reason the router metrics don't expose any 4xx? 
We actually need those 4xx metrics for debugging and alerting.

**Comment by jeremyeder** [comment]
Is this for 3.x or 4.x?  Does 4.x expose 4xx?

**Comment by smarterclayton** [comment]
We did this to minimize cardinality before

**Comment by smarterclayton** [comment]
I'm not opposed to it if it's easy to get.

**Comment by metalmatze** [comment]
I didn't see a difference between Openshift 3 and 4 in terms of router metrics.

**Comment by smarterclayton** [comment]
I will be fixing this, please open a product bug and assign to me for 4.5.

**Comment by jeremyeder** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1832629
