### ISSUE TITLE
Expose histogram for http requests

### ISSUE THREAD

**Issue by metalmatze** [openshift/router#82]
I can see that the router exposes `haproxy_server_http_average_response_latency_milliseconds` but that is not very helpful when trying to use metrics to calculate the 90th or 99th percentile for example. Is it possible to get these somehow from haproxy?

**Comment by jeremyeder** [comment]
Is this for 3.x or 4.x?

**Comment by smarterclayton** [comment]
Cardinality was the concern.  We have to scale to 100k routes (roughly), and any metric that couldn't scale to that limit or was a significant multiple was limited.

**Comment by brancz** [comment]
Having distribution of status code responses I think is sufficient as at that point we can measure duration on the backend itself. What’s necessary though is a general histogram if not already available as we recently had a situation where latency for all routes spiked momentarily.

**Comment by smarterclayton** [comment]
This is not supported by haproxy unfortunately.  The best we can do is what they expose.  I will be adding 1xx/2xx/3xx/4xx/5xx totals, but there is no way to do the breakdown here.
